//! The launch contract: what the client hands a plugin process when it starts it.
//!
//! Everything arrives through the environment. A running process cannot have its
//! environment changed, so a renewed platform token reaches the plugin only through a
//! response to a call it was making anyway — see [`crate::platform`].

use std::env;
use std::fmt;
use std::path::PathBuf;

use serde::Deserialize;

/// Port the local server must bind on `127.0.0.1`. Chosen by the client.
pub const ENV_PORT: &str = "AURIFY_PLUGIN_PORT";
/// Shared secret every local request must carry. Generated by the client per install.
pub const ENV_SECRET: &str = "AURIFY_PLUGIN_SECRET";
/// Base URL of the Aurify platform, e.g. `https://aurify.online`.
pub const ENV_PLATFORM_URL: &str = "AURIFY_PLATFORM_URL";
/// Token the plugin presents to the platform. Scoped to the plugin and the person.
pub const ENV_PLATFORM_TOKEN: &str = "AURIFY_PLATFORM_TOKEN";
/// Directory the plugin may write to. Uninstall removes what the manifest lists here.
pub const ENV_DATA_DIR: &str = "AURIFY_PLUGIN_DATA_DIR";

pub const MIN_SECRET_CHARS: usize = 16;

#[derive(Debug, Clone)]
pub struct LaunchContext {
    pub port: u16,
    pub secret: String,
    pub platform_url: Option<String>,
    pub platform_token: Option<String>,
    pub data_dir: Option<PathBuf>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LaunchError {
    Missing(&'static str),
    Invalid(&'static str, String),
}

impl fmt::Display for LaunchError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LaunchError::Missing(name) => write!(f, "{name} is not set: the plugin must be started by the Aurify client"),
            LaunchError::Invalid(name, why) => write!(f, "{name} is invalid: {why}"),
        }
    }
}

impl std::error::Error for LaunchError {}

/// The same five values as JSON, for a binding that reads the environment itself.
///
/// A host language does not always share the process environment with this library:
/// .NET on Unix keeps its own copy and never calls `setenv`, so a value set there is
/// invisible here. The binding reads the variables in its own runtime and hands them
/// over explicitly; the rules stay in one place either way.
#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LaunchValues {
    #[serde(default)]
    pub port: Option<String>,
    #[serde(default)]
    pub secret: Option<String>,
    #[serde(default)]
    pub platform_url: Option<String>,
    #[serde(default)]
    pub platform_token: Option<String>,
    #[serde(default)]
    pub data_dir: Option<String>,
}

impl LaunchContext {
    pub fn from_env() -> Result<Self, LaunchError> {
        Self::from_values(LaunchValues {
            port: env::var(ENV_PORT).ok(),
            secret: env::var(ENV_SECRET).ok(),
            platform_url: env::var(ENV_PLATFORM_URL).ok(),
            platform_token: env::var(ENV_PLATFORM_TOKEN).ok(),
            data_dir: env::var(ENV_DATA_DIR).ok(),
        })
    }

    pub fn from_json(json: &str) -> Result<Self, LaunchError> {
        let values: LaunchValues =
            serde_json::from_str(json).map_err(|e| LaunchError::Invalid("launch", format!("not valid JSON: {e}")))?;
        Self::from_values(values)
    }

    /// Every rule in one place, whichever way the values arrived. Missing values are
    /// reported by their environment name: that is the name a person will look for.
    pub fn from_values(values: LaunchValues) -> Result<Self, LaunchError> {
        let port_raw = non_empty(values.port).ok_or(LaunchError::Missing(ENV_PORT))?;
        let port: u16 = port_raw
            .trim()
            .parse()
            .map_err(|_| LaunchError::Invalid(ENV_PORT, format!("{port_raw:?} is not a port")))?;
        if port == 0 {
            return Err(LaunchError::Invalid(ENV_PORT, "0 is not a port".to_string()));
        }

        let secret = non_empty(values.secret).ok_or(LaunchError::Missing(ENV_SECRET))?;
        if secret.chars().count() < MIN_SECRET_CHARS {
            return Err(LaunchError::Invalid(ENV_SECRET, format!("shorter than {MIN_SECRET_CHARS} characters")));
        }

        Ok(Self {
            port,
            secret,
            platform_url: non_empty(values.platform_url),
            platform_token: non_empty(values.platform_token),
            data_dir: non_empty(values.data_dir).map(PathBuf::from),
        })
    }
}

fn non_empty(value: Option<String>) -> Option<String> {
    value.filter(|v| !v.trim().is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    use std::sync::Mutex;

    // Environment is process-wide and the test harness runs tests in parallel: without a
    // lock, one test's secret lands in another test's port check.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn with_env(pairs: &[(&str, Option<&str>)], run: impl FnOnce()) {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        for (name, value) in pairs {
            match value {
                Some(v) => env::set_var(name, v),
                None => env::remove_var(name),
            }
        }
        run();
        for (name, _) in pairs {
            env::remove_var(name);
        }
    }

    #[test]
    fn a_process_started_by_hand_is_told_so() {
        with_env(&[(ENV_PORT, None), (ENV_SECRET, None)], || {
            assert_eq!(LaunchContext::from_env().unwrap_err(), LaunchError::Missing(ENV_PORT));
        });
    }

    #[test]
    fn a_short_secret_is_refused() {
        with_env(&[(ENV_PORT, Some("43121")), (ENV_SECRET, Some("short"))], || {
            assert!(matches!(LaunchContext::from_env().unwrap_err(), LaunchError::Invalid(ENV_SECRET, _)));
        });
    }

    #[test]
    fn explicit_values_follow_the_same_rules_as_the_environment() {
        let ctx = LaunchContext::from_json(r#"{"port":"43121","secret":"0123456789abcdef","platformUrl":"https://x","dataDir":""}"#).unwrap();
        assert_eq!(ctx.port, 43121);
        assert_eq!(ctx.platform_url.as_deref(), Some("https://x"));
        assert!(ctx.data_dir.is_none());
        assert_eq!(LaunchContext::from_json(r#"{"secret":"0123456789abcdef"}"#).unwrap_err(), LaunchError::Missing(ENV_PORT));
        assert!(matches!(LaunchContext::from_json("{"), Err(LaunchError::Invalid("launch", _))));
    }

    #[test]
    fn optional_values_stay_absent_when_empty() {
        with_env(
            &[
                (ENV_PORT, Some("43121")),
                (ENV_SECRET, Some("0123456789abcdef")),
                (ENV_PLATFORM_URL, Some("")),
                (ENV_DATA_DIR, Some("  ")),
            ],
            || {
                let ctx = LaunchContext::from_env().unwrap();
                assert_eq!(ctx.port, 43121);
                assert!(ctx.platform_url.is_none());
                assert!(ctx.data_dir.is_none());
            },
        );
    }
}
